# rust-toolchain.toml
[toolchain]
channel = "stable"
targets = ["x86_64-unknown-linux-gnu"]
components = ["rustc", "cargo", "clippy", "rustfmt", "rust-analyzer"]

# Optional: Profile for faster builds in development
[env]
CARGO_PROFILE_DEV_DEBUG = "1"
RUST_LOG = "debug"
